name: Test
on:
  workflow_dispatch:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: pnpm build
        run: |
          pnpm run build

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
      

      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r lrseo_wp_plugin.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers**

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lrseo_wp_plugin
          path: lrseo_wp_plugin.zip
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lrseo_wp_plugin.zip
          asset_name: lrseo_wp_plugin.zip
          asset_content_type: application/zip

      
